POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "anandhusahe@gmail.com",
    "password": "testing@123"
}

###

POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "fname": "Anandhu",
    "lname": "Satheesh",
    "email": "anandhusahe@gmail.com",
    "password": "testing@123",
    "confirmPassword": "testing@123",
    "accountType": "home",
    "linkedUserId": "6668bc04da26b284fdb8962e",
    "linkedUserType": "agency"
}
    