
@homeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzYwZmJlNTMyZmMyNjYyNWU0OTMwNyIsImlhdCI6MTcxOTAxMzMxMCwiZXhwIjoxNzI2Nzg5MzEwfQ.028jxNHQAgsoqPvBMiOMD68O9Sy-GKJCOIseCD67OuY
@agencyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzYwZGRlMTQ3NTg1MWRmMjA4NGIyNiIsImlhdCI6MTcxOTAxMjgzMCwiZXhwIjoxNzI2Nzg4ODMwfQ.4Fvx5Z3ZH_ViqAs2SIDxLCFsj9zobQA64T5DL5pDyH8


### 

POST https://fc7e-82-44-21-31.ngrok-free.app/api/v1/auth/login
Content-Type: application/json

{
    "email": "anandhusathee@gmail.com",
    "password": "testing@123"
}

###

PUT http://localhost:4000/api/v1/auth/update-availability
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzFkYWRlZjlhODUxYWZmNGEzMThiZiIsImlhdCI6MTcxODczNzYzMCwiZXhwIjoxNzI2NTEzNjMwfQ.p6-oxZF_qOuxExEo9xoyPjFM31YaWSEJo_yNLJj9AmI

{
    "dates":[
        "2022-02-10"
    ]
}

###
DELETE http://localhost:4000/api/v1/auth/availabilities/2022-02-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzFkYWRlZjlhODUxYWZmNGEzMThiZiIsImlhdCI6MTcxODczNzYzMCwiZXhwIjoxNzI2NTEzNjMwfQ.p6-oxZF_qOuxExEo9xoyPjFM31YaWSEJo_yNLJj9AmI

###
GET http://localhost:4000/api/v1/auth/linked-users/home
Authorization: Bearer {{agencyToken}}
###

GET https://fc7e-82-44-21-31.ngrok-free.app/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzYwZGRlMTQ3NTg1MWRmMjA4NGIyNiIsImlhdCI6MTcxOTAxMjgzMCwiZXhwIjoxNzI2Nzg4ODMwfQ.4Fvx5Z3ZH_ViqAs2SIDxLCFsj9zobQA64T5DL5pDyH8
###

PATCH http://localhost:4000/api/v1/auth/link 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmI2ZWQ3MDIzMDhhMWJmZjI1NTZlYyIsImlhdCI6MTcxODMxNjc1OSwiZXhwIjoxNzI2MDkyNzU5fQ.ynP2PBwX3zOMKWeV_A9i5n4P-tueV9QEkqCFzWT_sDQ

{
    "linkedUserId": "666b6f4c02308a1bff2556fb",
    "linkedUserType": "home"
}

###

PATCH http://localhost:4000/api/v1/auth/unlink
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjhiYzA0ZGEyNmIyODRmZGI4OTYyZSIsImlhdCI6MTcxODEzOTkwOCwiZXhwIjoxNzI1OTE1OTA4fQ.UFV9dhcBjZRsTrViSAQm1bhBdy0DCI1v2Dzt1FvLtpQ

{
    "linkedUserId": "6668bc22da26b284fdb89638",
    "linkedUserType": "home"
}

###

POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "fname": "Marshal",
    "lname": "Sebastian",
    "email": "marshal@gmail.com",
    "password": "testing@123",
    "confirmPassword": "testing@123",
    "accountType": "agency",

}
    
###



GET http://localhost:4000/api/v1/auth/search-users/home?companyName=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzYwZGRlMTQ3NTg1MWRmMjA4NGIyNiIsImlhdCI6MTcxOTAxMjgzMCwiZXhwIjoxNzI2Nzg4ODMwfQ.4Fvx5Z3ZH_ViqAs2SIDxLCFsj9zobQA64T5DL5pDyH8