
GET http://localhost:4000/api/v1/shift
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NThmY2MzYjEzN2EzNzc4MTk1Nzc5YSIsImlhdCI6MTcxNzEwNzkwNywiZXhwIjoxNzI0ODgzOTA3fQ.aqKahZkdvAbWCec29BZRlWY0nqB9VBPAK_x_SsL-1fA

###
POST http://localhost:4000/api/v1/shift
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4
Content-Type: application/json

{
    "shiftType": "6664dc4b59ae9818cd22e7cf",
    "agentId": "6658fcc3b137a3778195779a",
    "count":2
}

###

DELETE http://localhost:4000/api/v1/shift/6664dc8159ae9818cd22e7df
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4


###

PUT http://localhost:4000/api/v1/shift/6664dc5e59ae9818cd22e7d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4
Content-Type: application/json

{
    "shiftType": "6664dc4b59ae9818cd22e7cf",
    "agentId": "6658fcc3b137a3778195779a",
    "count":10
}

###

GET http://localhost:4000/api/v1/shift/66638e8845c72520e7c177a0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4